### PR TITLE
Changes to DESCRIPTION, RBuildignore, .travis.yml

### PR DESCRIPTION
**Pull request by bpbond**
Added version numbers for all package dependencies; added @rplzzz to
get email on build failures; added comments to `.Rbuildignore`

### CODE REVIEW

**Review by rplzzz — APPROVED** [review]
I had left off version numbers for all of the packages that used version numbers of the form X.Y-Z instead of X.Y.Z.  I take it that the version test handles the '-' without any problems?

**Comment by bpbond** [comment]
I didn't put any numbers of that form in DESCRIPTION, but yeah, R CMD CHECK seems to be smart enough to figure it out.

**Comment by bpbond** [comment]
I'd just like to say that I love CI. So useful.

**Comment by rplzzz** [comment]
Yeah, it's good stuff.

I'll let you do the honors on this one.

**Pull request merged**
